config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :adventures
  resources :addresses
  resources :companies, param: :slug
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'companies#index'

  get '*slug', to: 'companies#show', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/adventure.rb
# frozen_string_literal: true

# Representing tracking of work (pictures, descriptions, tags, details)
class Adventure < ApplicationRecord
  enum status: { draft: 0, bid: 1, in_progress: 5, complete: 10 }
  enum shareable: { everyone: 0, followers: 3, party: 6, company_owners: 9, adventure_leaders: 15 }

  has_many :adventure_addresses
  has_many :addresses, through: :adventure_addresses
  accepts_nested_attributes_for :adventure_addresses

  # make its own model adventureImages so it can have descriptions / tags / interactions?
  has_many_attached :images do |attachable|
    attachable.variant :mobile, resize_to_limit: [200, 100]
  end

  before_validation :find_or_create_addresses

  def find_or_create_addresses
    adventure_addresses.each do |adventure_address|
      address_params = adventure_address.address
      adventure_address.address = Address.find_or_create_by(
        street_number: address_params.street_number,
        street: address_params.street,
        city: address_params.city,
        state: address_params.state
      )
    end
  end
end

app/controllers/adventures_controller.rb
# frozen_string_literal: true

# Tracking work events (adventures)
class AdventuresController < ApplicationController
  before_action :set_adventure, only: %i[show edit update destroy]

  # GET /adventures or /adventures.json
  def index
    @adventures = Adventure.all
  end

  # GET /adventures/1 or /adventures/1.json
  def show
  end

  # GET /adventures/new
  def new
    @adventure = Adventure.new
    @adventure.adventure_addresses.build.build_address
  end

  # GET /adventures/1/edit
  def edit
    @adventure.adventure_addresses.first&.build_address if @adventure.addresses.empty?
  end

  # POST /adventures or /adventures.json
  def create
    @adventure = Adventure.new(adventure_params)

    respond_to do |format|
      if @adventure.save
        format.html { redirect_to adventure_url(@adventure), notice: 'Adventure was successfully created.' }
        format.json { render :show, status: :created, location: @adventure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adventures/1 or /adventures/1.json
  def update
    respond_to do |format|
      if @adventure.update(adventure_params)
        format.html { redirect_to adventure_url(@adventure), notice: 'Adventure was successfully updated.' }
        format.json { render :show, status: :ok, location: @adventure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1 or /adventures/1.json
  def destroy
    @adventure.destroy!

    respond_to do |format|
      format.html { redirect_to adventures_url, notice: 'Adventure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_adventure
    @adventure = Adventure.includes(:addresses).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def adventure_params
    params.require(:adventure).permit(
      :title,
      :description,
      :status,
      :shareable,
      :active,
      :target_completion,
      adventure_addresses_attributes: [:description, :id,
        address_attributes: [:id, :street_number, :street, :city, :state, :postal_code, :location_type]
      ]
    )
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/views/adventures/_adventure.html.erb
<div id="<%= dom_id adventure %>">
  <p>
    <strong>Title:</strong>
    <%= adventure.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= adventure.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= adventure.status %>
  </p>

  <p>
    <strong>Shareable:</strong>
    <%= adventure.shareable %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= adventure.active %>
  </p>

  <p>
    <strong>Target completion:</strong>
    <%= adventure.target_completion %>
  </p>

</div>

app/views/adventures/_form.html.erb
<%= form_with(model: adventure) do |form| %>
  <% if adventure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
        <% adventure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, { select: Adventure.statuses.keys }, include_blank: true %>
  </div>

  <div>
    <%= form.label :shareable, style: "display: block" %>
    <%= form.select :shareable, { select: Adventure.shareables.keys }, include_blank: true %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :target_completion, style: "display: block" %>
    <%= form.datetime_field :target_completion %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  <% if @adventure.addresses.present? || true %>
    <h3>Addresses</h3>
    <%= form.fields_for :adventure_addresses do |adventure_address_form| %>
      <%= adventure_address_form.label :description, style: "display: block" %>
      <%= adventure_address_form.text_area :description %>
      <%= adventure_address_form.fields_for :address do |addresses_form| %>
        <%= addresses_form.label :city, style: "display: block" %>
        <%= addresses_form.text_field :city, required: true %>

        <div>
          <%= addresses_form.label :street_number, style: "display: block" %>
          <%= addresses_form.text_field :street_number, autocomplete: "off", required: true%>
        </div>

        <div>
          <%= addresses_form.label :street, "Street name ", style: "display: block" %>
          <%= addresses_form.text_field :street, required: true %>
        </div>
        <div>
          <%= addresses_form.label :postal_code, style: "display: block" %>
          <%= addresses_form.text_field :postal_code %>
        </div>
        <div>
          <%= addresses_form.label :state, style: "display: block" %>
          <%= addresses_form.text_field :state %>
        </div>
      <% end %>
    <% end %>
  <% end %>

<% end %>

app/views/adventures/edit.html.erb
<h1>Editing adventure</h1>

<%= render "form", adventure: @adventure %>

<br>

<div>
  <%= link_to "Show this adventure", @adventure %> |
  <%= link_to "Back to adventures", adventures_path %>
</div>

app/views/adventures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Adventures</h1>

<div id="adventures">
  <% @adventures.each do |adventure| %>
    <%= render adventure %>
    <p>
      <%= link_to "Show this adventure", adventure %>
    </p>
  <% end %>
</div>

<%= link_to "New adventure", new_adventure_path %>

app/views/adventures/new.html.erb
<h1>New adventure</h1>

<%= render "form", adventure: @adventure %>

<br>

<div>
  <%= link_to "Back to adventures", adventures_path %>
</div>

app/views/adventures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @adventure %>

<div>
  <%= link_to "Edit this adventure", edit_adventure_path(@adventure) %> |
  <%= link_to "Back to adventures", adventures_path %>

  <%= button_to "Destroy this adventure", @adventure, method: :delete %>
</div>