config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :adventures
  resources :addresses
  resources :companies, param: :slug
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'companies#index'

  get '*slug', to: 'companies#show', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/controllers/addresses_controller.rb
# frozen_string_literal: true

# Path locations and form response methods
class AddressesController < ApplicationController
  before_action :set_address, only: %i[show edit update destroy]
  before_action :set_state_options, only: %i[new edit update]
  before_action :set_county_options, only: %i[new edit update]

  require 'fips_lookup'

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new address_params
  end

  # GET /addresses/1/edit
  def edit
    @address.assign_attributes address_params unless address_params.empty? || @address.errors.present?
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy!

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_address
    @address = Address.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def address_params
    params.fetch(:address, {}).permit(:street, :postal_code, :street_number, :city, :state, :county, :fips_code, :country, :location_type)
  end

  def set_state_options
    @state_options = [] # select options [display name, form value]
    CSV.foreach(FipsLookup.state_file) do |state_row|
      @state_options << [state_row[2], state_row[1]]
    end
  end

  def set_county_options
    return unless FipsLookup::STATE_CODES.key?(address_params[:state] || @address&.state)

    state_code = address_params[:state] || @address.state
    @county_options = []
    CSV.foreach(FipsLookup.county_file(state_code:)) do |county_row|
      @county_options << county_row[3]
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>Street:</strong>
    <%= address.street %>
  </p>

  <p>
    <strong>Postal code:</strong>
    <%= address.postal_code %>
  </p>

  <p>
    <strong>Street number:</strong>
    <%= address.street_number %>
  </p>

  <p>
    <strong>City:</strong>
    <%= address.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= address.state %>
  </p>

  <p>
    <strong>County:</strong>
    <%= address.county %>
  </p>

  <p>
    <strong>Fips code:</strong>
    <%= address.fips_code %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= address.country %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: @address, class: "flex flex-col gap-2")  do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :street_number, style: "display: block" %>
    <%= form.text_field :street_number, autocomplete: "off", required: true%>
  </div>

  <div>
    <%= form.label :street, "Street name ", style: "display: block" %>
    <%= form.text_field :street, required: true %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city, required: true %>
  </div>

  <div>
    <%= form.label :postal_code, style: "display: block" %>
    <%= form.text_field :postal_code %>
  </div>

  <fieldset class="contents" data-controller="address">
    <div>
      <%= form.label :state, style: "display: block" %>
      <%= form.select :state, @state_options, {prompt: "-select-"},
        data: { action: "change->address#click" } %>
    </div>

    <% if @county_options.present? %>
      <div>
        <%= form.label :county, style: "display: block" %>
        <%= form.select :county, @county_options %>
      </div>
    <% end %>
    
    <button formmethod="get" formaction="<%= request.url %>" hidden
      data-address-target="click">
    </button>
  </fieldset>

  <div>
    <%= form.label :location_type, style: "display: block" %>
    <%= form.select :location_type, { select: Address.location_types.keys }, include_blank: true %>
  </div>

  <!-- # hidden forms with values from object? -->
  <div>
    <!-- # add in from county row selection? -->
    <% form.label :fips_code, style: "display: block" %>
    <% form.text_field :fips_code %>
  </div>

  <div>
    <!-- # add city-state gem ? to list countries and states outside US  -->
    <% form.label :country, style: "display: block" %>
    <%  form.text_field :country %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Show this address", @address %> |
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Addresses</h1>

<div id="addresses">
  <% @addresses.each do |address| %>
    <%= render address %>
    <p>
      <%= link_to "Show this address", address %>
    </p>
  <% end %>
</div>

<%= link_to "New address", new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @address %>

<div>
  <%= link_to "Edit this address", edit_address_path(@address) %> |
  <%= link_to "Back to addresses", addresses_path %>

  <%= button_to "Destroy this address", @address, method: :delete %>
</div>